=== pkg-mngr/pkg/package.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the project"
    },
    "description": {
      "type": "string",
      "description": "A short description of the project"
    },
    "homepage": {
      "type": "string",
      "description": "A link to the project's homepage"
    },
    "version": {
      "type": "string",
      "description": "The version of the package being installed"
    },
    "sha256": {
      "type": "string",
      "description": "The SHA256 checksum of the file being downloaded"
    },
    "url": {
      "type": "string",
      "description": "The URL to the file being downloaded"
    },
    "dependencies": {
      "type": "array",
      "description": "Other packages that this package depends on",
      "items": { "type": "string" }
    },
    "caveats": {
      "type": "string",
      "description": "Extra information the user should know after installation completes, such as setup information"
    },
    "scripts": {
      "type": "object",
      "properties": {
        "install": {
          "type": "array",
          "description": "The script to run to install the package after downloading",
          "items": { "type": "string" }
        },
        "latest": {
          "type": "array",
          "description": "The script to run to check the latest version of the package",
          "items": { "type": "string" },
          "default": [
            "gh release list -R OWNER/REPO --json tagName --jq '.[0].tagName' | cut -c 2-"
          ]
        },
        "completions": {
          "type": "array",
          "description": "The script to run to install ZSH shell completions for the package",
          "items": { "type": "string" }
        }
      },
      "required": ["install", "latest"]
    }
  },
  "required": [
    "name",
    "description",
    "homepage",
    "version",
    "sha256",
    "url",
    "scripts"
  ]
}

=== pkg-mngr/pkg/packages/pkg.json
{
  "$schema": "../package.schema.json",
  "name": "pkg",
  "description": "A simple package manager for macOS",
  "homepage": "https://pkg.zerolimits.dev",
  "version": "0.1.8",
  "sha256": "2e16fa73e34f14daa930f7cb3149c609568c7e68d9ecf1134ee9ef691d072d7e",
  "url": "https://github.com/noClaps/pkg/releases/download/v{{ version }}/pkg.tar.xz",
  "scripts": {
    "install": [
      "tar -xf pkg.tar.xz",
      "install pkg {{ pkg.bin_dir }}/pkg"
    ],
    "latest": [
      "gh release list -R noClaps/pkg --json tagName --jq '.[0].tagName' | cut -c 2-"
    ],
    "completions": [
      "pkg --completions zsh > {{ pkg.completions.zsh }}/_pkg"
    ]
  }
}
